name: Hourly Proxy Update

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-links:
    runs-on: ubuntu-latest
    steps:
    - name: Проверка репозитория
      uses: actions/checkout@v4

    - name: Установка Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Установка библиотек
      run: pip install requests

    - name: Запуск чекера
      run: python script.py

    - name: Сохранение изменений в GitHub
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add vlessbs
        git commit -m "Авто-обновление прокси: $(date)" || echo "Нет изменений"
        git push
